### ISSUE TITLE
RangeError: Maximum call stack size exceeded on a recursive interface

### ISSUE THREAD

**Issue by usersina** [yantrab/nest-openapi-gen#8]
Very neat project! It worked quite well so far, but I had a very specific use case that required the infamous **recursion**, which broke the generation.

```typescript
interface SimpleTag {
  tagId: number;
  name: string;
}

interface ExpandedTagWithParents extends SimpleTag {
  parentTags: ExpandedTagWithParents[] | null;
}

@Controller('tags')
export class TagsController {
  constructor(private readonly tagsService: TagsService) {}

  @Get(':tagId/parents/expanded')
  async getExpandedTags(@Param('tagId') tagId: number): Promise<ExpandedTagWithParents> {
    return this.tagsService.getExpandedTagsWithParents(tagId);
  }
}
```

Here's the call stack:

```
> ts-node openapi.generator.ts

path/to/my-project/node_modules/@ts-morph/common/dist/typescript.js:46427
        function resolveAlias(symbol) {
                             ^
RangeError: Maximum call stack size exceeded
    at resolveAlias path/to/my-project/node_modules/@ts-morph/common/dist/typescript.js:46427:30)
    at path/to/my-project/node_modules/@ts-morph/common/dist/typescript.js:47381:54
    at Object.forEachEntry path/to/my-project/node_modules/@ts-morph/common/dist/typescript.js:13601:26)
    at trySymbolTable path/to/my-project/node_modules/@ts-morph/common/dist/typescript.js:47371:33)
    at getAccessibleSymbolChainFromSymbolTable path/to/my-project/node_modules/@ts-morph/common/dist/typescript.js:47347:30)
    at getCandidateListForSymbol path/to/my-project/node_modules/@ts-morph/common/dist/typescript.js:47403:70)
    at path/to/my-project/node_modules/@ts-morph/common/dist/typescript.js:47382:41
    at Object.forEachEntry path/to/my-project/node_modules/@ts-morph/common/dist/typescript.js:13601:26)
    at trySymbolTable path/to/my-project/node_modules/@ts-morph/common/dist/typescript.js:47371:33)
    at getAccessibleSymbolChainFromSymbolTable path/to/my-project/node_modules/@ts-morph/common/dist/typescript.js:47347:30)
```

I am happy to contribute.

**Comment by yantrab** [comment]
Thank you for the compliment! I'm glad to hear the project worked well for you.

The project hasn't been updated for quite some time. 
It seems the problem lies with ts-morph, in trying to get the method return type.
Feel free to try updating the library to see if it resolves the problem. 
Unfortunately, I don't have the time to address this right now.

Thanks again for your willingness to contribute!

**Comment by usersina** [comment]
There you go! I really hope I can use this project for my future production-ready microservices :)

https://github.com/yantrab/nest-openapi-gen/pull/9
